runtime: nodejs12 # or another supported version

instance_class: F2

env_variables:
  #BUCKET_NAME: "example-gcs-bucket"
  MONGO_USERNAME: greenThumbBois
  MONGO_PASSWORD: 3f3fvk8HW88mm3Ag

handlers:
  
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
  static_files: client/build/index.html
  upload: client/build/index.html
  static_dir: client/build 