runtime: nodejs12 # or another supported version

instance_class: F2

env_variables:
  #BUCKET_NAME: "example-gcs-bucket"
  MONGO_USERNAME: greenThumbBois
  MONGO_PASSWORD: 3f3fvk8HW88mm3Ag

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /
    static_dir: build
